### ISSUE TITLE
Codalab evaluation fails

### ISSUE THREAD

**Issue by dhpitt** [eccv22-ood-workshop/ROBIN-dataset#30]
Hi,

I uploaded a directory of results with the required format and I get an error in Codalab:

my directory structure is as follows:

file_name.zip
--iid.csv
--context.csv
--occlusion.csv
--weather.csv
--shape.csv
--pose.csv
--texture.csv

The error I get is:

WARNING: Your kernel does not support swap limit capabilities or the cgroup is not mounted. Memory limited without swap.
Traceback (most recent call last):
  File "/tmp/codalab/tmpLxQx43/run/program/main.py", line 171, in 
    main()
  File "/tmp/codalab/tmpLxQx43/run/program/main.py", line 77, in main
    iid_pred = pd.read_csv(osp.join(args.input, 'res', 'iid.csv'))
  File "/usr/local/lib/python3.6/dist-packages/pandas/io/parsers.py", line 686, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/usr/local/lib/python3.6/dist-packages/pandas/io/parsers.py", line 452, in _read
    parser = TextFileReader(fp_or_buf, **kwds)
  File "/usr/local/lib/python3.6/dist-packages/pandas/io/parsers.py", line 936, in __init__
    self._make_engine(self.engine)
  File "/usr/local/lib/python3.6/dist-packages/pandas/io/parsers.py", line 1168, in _make_engine
    self._engine = CParserWrapper(self.f, **self.options)
  File "/usr/local/lib/python3.6/dist-packages/pandas/io/parsers.py", line 1998, in __init__
    self._reader = parsers.TextReader(src, **kwds)
  File "pandas/_libs/parsers.pyx", line 361, in pandas._libs.parsers.TextReader.__cinit__
  File "pandas/_libs/parsers.pyx", line 653, in pandas._libs.parsers.TextReader._setup_parser_source
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/codalab/tmpLxQx43/run/input/res/iid.csv'

**Comment by wjm-wjm** [comment]
Maybe your unzipped file contains the source dir?

**Comment by dhpitt** [comment]
> Maybe your unzipped file contains the source dir?

That was it. Thank you for the help!

**Comment by wjm-wjm** [comment]
Good luck! ^.^
